# Generated by Django 5.0.2 on 2024-08-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url1', models.CharField(max_length=255)),
                ('url2', models.CharField(max_length=255)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
